//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justice.NotariatService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchParam", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class SearchParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Justice.NotariatService.SearchType SearchTypeField;
        
        private Justice.NotariatService.SearchDocument DocumentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Justice.NotariatService.SearchType SearchType {
            get {
                return this.SearchTypeField;
            }
            set {
                if ((this.SearchTypeField.Equals(value) != true)) {
                    this.SearchTypeField = value;
                    this.RaisePropertyChanged("SearchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public Justice.NotariatService.SearchDocument Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchDocument", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class SearchDocument : Justice.NotariatService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.DocType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.SearchPerson PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAddressSpecifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPhotoSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Series {
            get {
                return this.SeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesField, value) != true)) {
                    this.SeriesField = value;
                    this.RaisePropertyChanged("Series");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Justice.NotariatService.DocType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string DocDateStr {
            get {
                return this.DocDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.DocDateStrField, value) != true)) {
                    this.DocDateStrField = value;
                    this.RaisePropertyChanged("DocDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Justice.NotariatService.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Justice.NotariatService.SearchPerson Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Justice.NotariatService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool IsAddressSpecified {
            get {
                return this.IsAddressSpecifiedField;
            }
            set {
                if ((this.IsAddressSpecifiedField.Equals(value) != true)) {
                    this.IsAddressSpecifiedField = value;
                    this.RaisePropertyChanged("IsAddressSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool IsPhotoSpecified {
            get {
                return this.IsPhotoSpecifiedField;
            }
            set {
                if ((this.IsPhotoSpecifiedField.Equals(value) != true)) {
                    this.IsPhotoSpecifiedField = value;
                    this.RaisePropertyChanged("IsPhotoSpecified");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchType", Namespace="https://reyestr.gov.az")]
    public enum SearchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonByPin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonByVesksKod = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonByDocNumber = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonsByDetails = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonsByLike = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocumentByNumber = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocumentsByName = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocumentsByPin = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RelationsByPin = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CertificateByNumber = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeadPersonsByDetails = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CertificateByBirthDate = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WatchPersonByPeriod = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WatchPersonByDocNumber = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocumentsByDetails = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocumentsByNameWithoutDOB = 20,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.SearchPerson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.FullDocument))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.Person))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.FullPerson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.SearchDocument))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchPerson", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class SearchPerson : Justice.NotariatService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VesksKodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfBirthStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfBirthEndStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Place BirthPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.BloodGroup BloodGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.EyeColor EyeColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateDateStrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinDateStr {
            get {
                return this.PinDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.PinDateStrField, value) != true)) {
                    this.PinDateStrField = value;
                    this.RaisePropertyChanged("PinDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VesksKod {
            get {
                return this.VesksKodField;
            }
            set {
                if ((object.ReferenceEquals(this.VesksKodField, value) != true)) {
                    this.VesksKodField = value;
                    this.RaisePropertyChanged("VesksKod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string DateOfBirthStr {
            get {
                return this.DateOfBirthStrField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfBirthStrField, value) != true)) {
                    this.DateOfBirthStrField = value;
                    this.RaisePropertyChanged("DateOfBirthStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string DateOfBirthEndStr {
            get {
                return this.DateOfBirthEndStrField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfBirthEndStrField, value) != true)) {
                    this.DateOfBirthEndStrField = value;
                    this.RaisePropertyChanged("DateOfBirthEndStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public Justice.NotariatService.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public Justice.NotariatService.Place BirthPlace {
            get {
                return this.BirthPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthPlaceField, value) != true)) {
                    this.BirthPlaceField = value;
                    this.RaisePropertyChanged("BirthPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Citizenship {
            get {
                return this.CitizenshipField;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenshipField, value) != true)) {
                    this.CitizenshipField = value;
                    this.RaisePropertyChanged("Citizenship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public Justice.NotariatService.BloodGroup BloodGroup {
            get {
                return this.BloodGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.BloodGroupField, value) != true)) {
                    this.BloodGroupField = value;
                    this.RaisePropertyChanged("BloodGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public Justice.NotariatService.EyeColor EyeColor {
            get {
                return this.EyeColorField;
            }
            set {
                if ((object.ReferenceEquals(this.EyeColorField, value) != true)) {
                    this.EyeColorField = value;
                    this.RaisePropertyChanged("EyeColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public byte Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string CreateDateStr {
            get {
                return this.CreateDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateStrField, value) != true)) {
                    this.CreateDateStrField = value;
                    this.RaisePropertyChanged("CreateDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string UpdateDateStr {
            get {
                return this.UpdateDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateDateStrField, value) != true)) {
                    this.UpdateDateStrField = value;
                    this.RaisePropertyChanged("UpdateDateStr");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullDocument", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class FullDocument : Justice.NotariatService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.DocType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssuingLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.FullPerson PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Photo PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpireDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvalidationDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvalidationReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Series {
            get {
                return this.SeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesField, value) != true)) {
                    this.SeriesField = value;
                    this.RaisePropertyChanged("Series");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Justice.NotariatService.DocType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string DocDateStr {
            get {
                return this.DocDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.DocDateStrField, value) != true)) {
                    this.DocDateStrField = value;
                    this.RaisePropertyChanged("DocDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string IssuingLocation {
            get {
                return this.IssuingLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuingLocationField, value) != true)) {
                    this.IssuingLocationField = value;
                    this.RaisePropertyChanged("IssuingLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Justice.NotariatService.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Justice.NotariatService.FullPerson Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public Justice.NotariatService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public Justice.NotariatService.Photo Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string ExpireDateStr {
            get {
                return this.ExpireDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpireDateStrField, value) != true)) {
                    this.ExpireDateStrField = value;
                    this.RaisePropertyChanged("ExpireDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string InvalidationDateStr {
            get {
                return this.InvalidationDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.InvalidationDateStrField, value) != true)) {
                    this.InvalidationDateStrField = value;
                    this.RaisePropertyChanged("InvalidationDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string InvalidationReason {
            get {
                return this.InvalidationReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.InvalidationReasonField, value) != true)) {
                    this.InvalidationReasonField = value;
                    this.RaisePropertyChanged("InvalidationReason");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.FullPerson))]
    public partial class Person : Justice.NotariatService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfBirthStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenshipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string DateOfBirthStr {
            get {
                return this.DateOfBirthStrField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfBirthStrField, value) != true)) {
                    this.DateOfBirthStrField = value;
                    this.RaisePropertyChanged("DateOfBirthStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Justice.NotariatService.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Citizenship {
            get {
                return this.CitizenshipField;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenshipField, value) != true)) {
                    this.CitizenshipField = value;
                    this.RaisePropertyChanged("Citizenship");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullPerson", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class FullPerson : Justice.NotariatService.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfDeathStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Place BirthPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.MaritalStatus MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.MilitaryStatus MilitaryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.BloodGroup BloodGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.EyeColor EyeColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateStrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinDateStr {
            get {
                return this.PinDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.PinDateStrField, value) != true)) {
                    this.PinDateStrField = value;
                    this.RaisePropertyChanged("PinDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DateOfDeathStr {
            get {
                return this.DateOfDeathStrField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfDeathStrField, value) != true)) {
                    this.DateOfDeathStrField = value;
                    this.RaisePropertyChanged("DateOfDeathStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Justice.NotariatService.Place BirthPlace {
            get {
                return this.BirthPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthPlaceField, value) != true)) {
                    this.BirthPlaceField = value;
                    this.RaisePropertyChanged("BirthPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Justice.NotariatService.MaritalStatus MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((this.MaritalStatusField.Equals(value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Justice.NotariatService.MilitaryStatus MilitaryStatus {
            get {
                return this.MilitaryStatusField;
            }
            set {
                if ((this.MilitaryStatusField.Equals(value) != true)) {
                    this.MilitaryStatusField = value;
                    this.RaisePropertyChanged("MilitaryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Justice.NotariatService.BloodGroup BloodGroup {
            get {
                return this.BloodGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.BloodGroupField, value) != true)) {
                    this.BloodGroupField = value;
                    this.RaisePropertyChanged("BloodGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Justice.NotariatService.EyeColor EyeColor {
            get {
                return this.EyeColorField;
            }
            set {
                if ((object.ReferenceEquals(this.EyeColorField, value) != true)) {
                    this.EyeColorField = value;
                    this.RaisePropertyChanged("EyeColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public byte Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CreateDateStr {
            get {
                return this.CreateDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateStrField, value) != true)) {
                    this.CreateDateStrField = value;
                    this.RaisePropertyChanged("CreateDateStr");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocType", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class DocType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Organ OrganNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.Organ OrganName {
            get {
                return this.OrganNameField;
            }
            set {
                if ((this.OrganNameField.Equals(value) != true)) {
                    this.OrganNameField = value;
                    this.RaisePropertyChanged("OrganName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Place TerritoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateStrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.Place Territory {
            get {
                return this.TerritoryField;
            }
            set {
                if ((object.ReferenceEquals(this.TerritoryField, value) != true)) {
                    this.TerritoryField = value;
                    this.RaisePropertyChanged("Territory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Apt {
            get {
                return this.AptField;
            }
            set {
                if ((object.ReferenceEquals(this.AptField, value) != true)) {
                    this.AptField = value;
                    this.RaisePropertyChanged("Apt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string House {
            get {
                return this.HouseField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseField, value) != true)) {
                    this.HouseField = value;
                    this.RaisePropertyChanged("House");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Justice.NotariatService.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CreateDateStr {
            get {
                return this.CreateDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateStrField, value) != true)) {
                    this.CreateDateStrField = value;
                    this.RaisePropertyChanged("CreateDateStr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="https://reyestr.gov.az")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Passive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Place", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class Place : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsoCode {
            get {
                return this.IsoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IsoCodeField, value) != true)) {
                    this.IsoCodeField = value;
                    this.RaisePropertyChanged("IsoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BloodGroup", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class BloodGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EyeColor", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class EyeColor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="https://reyestr.gov.az")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Photo", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class Photo : Justice.NotariatService.MediaFile {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organ", Namespace="https://reyestr.gov.az")]
    public enum Organ : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARIS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IAMAS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VMMS = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaritalStatus", Namespace="https://reyestr.gov.az")]
    public enum MaritalStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Married = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MilitaryStatus", Namespace="https://reyestr.gov.az")]
    public enum MilitaryStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMil = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MilSvc = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaFile", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.Photo))]
    public partial class MediaFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileBinaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileLength {
            get {
                return this.FileLengthField;
            }
            set {
                if ((this.FileLengthField.Equals(value) != true)) {
                    this.FileLengthField = value;
                    this.RaisePropertyChanged("FileLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FileBinary {
            get {
                return this.FileBinaryField;
            }
            set {
                if ((object.ReferenceEquals(this.FileBinaryField, value) != true)) {
                    this.FileBinaryField = value;
                    this.RaisePropertyChanged("FileBinary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.FullPersonListResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.FullDocListResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.FullDocSearchResult))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.ResultType ResultTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.BrokenRule[] RulesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.ResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.BrokenRule[] Rules {
            get {
                return this.RulesField;
            }
            set {
                if ((object.ReferenceEquals(this.RulesField, value) != true)) {
                    this.RulesField = value;
                    this.RaisePropertyChanged("Rules");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullPersonListResult", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class FullPersonListResult : Justice.NotariatService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.FullPerson[] PersonsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.FullPerson[] Persons {
            get {
                return this.PersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonsField, value) != true)) {
                    this.PersonsField = value;
                    this.RaisePropertyChanged("Persons");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullDocListResult", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class FullDocListResult : Justice.NotariatService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.FullDocument[] DocumentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.FullDocument[] Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullDocSearchResult", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class FullDocSearchResult : Justice.NotariatService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.FullDocument DocumentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.FullDocument Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultType", Namespace="https://reyestr.gov.az")]
    public enum ResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InformationFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultiDocFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultiPersonFound = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokenRule", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class BrokenRule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.RuleType BrokenRuleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.RuleType BrokenRuleType {
            get {
                return this.BrokenRuleTypeField;
            }
            set {
                if ((this.BrokenRuleTypeField.Equals(value) != true)) {
                    this.BrokenRuleTypeField = value;
                    this.RaisePropertyChanged("BrokenRuleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuleType", Namespace="https://reyestr.gov.az")]
    public enum RuleType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchByPinReq", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class SearchByPinReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.AddPersonRelationInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Justice.NotariatService.SearchByPinResult))]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.RegistryResultType ResultTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.ValidationRule[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.RegistryResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Justice.NotariatService.ValidationRule[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddPersonRelationInfoResult", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class AddPersonRelationInfoResult : Justice.NotariatService.BaseResult {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchByPinResult", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class SearchByPinResult : Justice.NotariatService.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.PersonInfo PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Relation[] RelationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.PersonInfo Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.Relation[] Relations {
            get {
                return this.RelationsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationsField, value) != true)) {
                    this.RelationsField = value;
                    this.RaisePropertyChanged("Relations");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistryResultType", Namespace="https://reyestr.gov.az")]
    public enum RegistryResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonNotFound = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationRule", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class ValidationRule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonInfo", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class PersonInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Gender GenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfBirthField, value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Justice.NotariatService.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relation", Namespace="https://reyestr.gov.az")]
    [System.SerializableAttribute()]
    public partial class Relation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.RegistryRelationType RelationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.PersonInfo PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.RegistryRelationStatus RelationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.RegistryRelationType RelationType {
            get {
                return this.RelationTypeField;
            }
            set {
                if ((this.RelationTypeField.Equals(value) != true)) {
                    this.RelationTypeField = value;
                    this.RaisePropertyChanged("RelationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Justice.NotariatService.PersonInfo Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Justice.NotariatService.RegistryRelationStatus RelationStatus {
            get {
                return this.RelationStatusField;
            }
            set {
                if ((this.RelationStatusField.Equals(value) != true)) {
                    this.RelationStatusField = value;
                    this.RaisePropertyChanged("RelationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistryRelationType", Namespace="https://reyestr.gov.az")]
    public enum RegistryRelationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spouse = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Father = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mother = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Child = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistryRelationStatus", Namespace="https://reyestr.gov.az")]
    public enum RegistryRelationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddPersonRelationInfoReq", Namespace="http://schemas.datacontract.org/2004/07/Registry.Core.Services.WCF.Models.Registr" +
        "yNotariat.Request")]
    [System.SerializableAttribute()]
    public partial class AddPersonRelationInfoReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Justice.NotariatService.Relation[] RelationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Justice.NotariatService.Relation[] Relations {
            get {
                return this.RelationsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationsField, value) != true)) {
                    this.RelationsField = value;
                    this.RaisePropertyChanged("Relations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://reyestr.gov.az", ConfigurationName="NotariatService.INotariatService")]
    public interface INotariatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/GetOneDocument", ReplyAction="https://reyestr.gov.az/INotariatService/GetOneDocumentResponse")]
        Justice.NotariatService.FullDocSearchResult GetOneDocument(Justice.NotariatService.SearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/GetOneDocument", ReplyAction="https://reyestr.gov.az/INotariatService/GetOneDocumentResponse")]
        System.Threading.Tasks.Task<Justice.NotariatService.FullDocSearchResult> GetOneDocumentAsync(Justice.NotariatService.SearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/GetDeadPersons", ReplyAction="https://reyestr.gov.az/INotariatService/GetDeadPersonsResponse")]
        Justice.NotariatService.FullPersonListResult GetDeadPersons(Justice.NotariatService.SearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/GetDeadPersons", ReplyAction="https://reyestr.gov.az/INotariatService/GetDeadPersonsResponse")]
        System.Threading.Tasks.Task<Justice.NotariatService.FullPersonListResult> GetDeadPersonsAsync(Justice.NotariatService.SearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/GetDocumentList", ReplyAction="https://reyestr.gov.az/INotariatService/GetDocumentListResponse")]
        Justice.NotariatService.FullDocListResult GetDocumentList(Justice.NotariatService.SearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/GetDocumentList", ReplyAction="https://reyestr.gov.az/INotariatService/GetDocumentListResponse")]
        System.Threading.Tasks.Task<Justice.NotariatService.FullDocListResult> GetDocumentListAsync(Justice.NotariatService.SearchParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/GetPersonByPin", ReplyAction="https://reyestr.gov.az/INotariatService/GetPersonByPinResponse")]
        Justice.NotariatService.SearchByPinResult GetPersonByPin(Justice.NotariatService.SearchByPinReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/GetPersonByPin", ReplyAction="https://reyestr.gov.az/INotariatService/GetPersonByPinResponse")]
        System.Threading.Tasks.Task<Justice.NotariatService.SearchByPinResult> GetPersonByPinAsync(Justice.NotariatService.SearchByPinReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/AddPersonRelationInfo", ReplyAction="https://reyestr.gov.az/INotariatService/AddPersonRelationInfoResponse")]
        Justice.NotariatService.AddPersonRelationInfoResult AddPersonRelationInfo(Justice.NotariatService.AddPersonRelationInfoReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://reyestr.gov.az/INotariatService/AddPersonRelationInfo", ReplyAction="https://reyestr.gov.az/INotariatService/AddPersonRelationInfoResponse")]
        System.Threading.Tasks.Task<Justice.NotariatService.AddPersonRelationInfoResult> AddPersonRelationInfoAsync(Justice.NotariatService.AddPersonRelationInfoReq request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotariatServiceChannel : Justice.NotariatService.INotariatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotariatServiceClient : System.ServiceModel.ClientBase<Justice.NotariatService.INotariatService>, Justice.NotariatService.INotariatService {
        
        public NotariatServiceClient() {
        }
        
        public NotariatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotariatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotariatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotariatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Justice.NotariatService.FullDocSearchResult GetOneDocument(Justice.NotariatService.SearchParam param) {
            return base.Channel.GetOneDocument(param);
        }
        
        public System.Threading.Tasks.Task<Justice.NotariatService.FullDocSearchResult> GetOneDocumentAsync(Justice.NotariatService.SearchParam param) {
            return base.Channel.GetOneDocumentAsync(param);
        }
        
        public Justice.NotariatService.FullPersonListResult GetDeadPersons(Justice.NotariatService.SearchParam param) {
            return base.Channel.GetDeadPersons(param);
        }
        
        public System.Threading.Tasks.Task<Justice.NotariatService.FullPersonListResult> GetDeadPersonsAsync(Justice.NotariatService.SearchParam param) {
            return base.Channel.GetDeadPersonsAsync(param);
        }
        
        public Justice.NotariatService.FullDocListResult GetDocumentList(Justice.NotariatService.SearchParam param) {
            return base.Channel.GetDocumentList(param);
        }
        
        public System.Threading.Tasks.Task<Justice.NotariatService.FullDocListResult> GetDocumentListAsync(Justice.NotariatService.SearchParam param) {
            return base.Channel.GetDocumentListAsync(param);
        }
        
        public Justice.NotariatService.SearchByPinResult GetPersonByPin(Justice.NotariatService.SearchByPinReq request) {
            return base.Channel.GetPersonByPin(request);
        }
        
        public System.Threading.Tasks.Task<Justice.NotariatService.SearchByPinResult> GetPersonByPinAsync(Justice.NotariatService.SearchByPinReq request) {
            return base.Channel.GetPersonByPinAsync(request);
        }
        
        public Justice.NotariatService.AddPersonRelationInfoResult AddPersonRelationInfo(Justice.NotariatService.AddPersonRelationInfoReq request) {
            return base.Channel.AddPersonRelationInfo(request);
        }
        
        public System.Threading.Tasks.Task<Justice.NotariatService.AddPersonRelationInfoResult> AddPersonRelationInfoAsync(Justice.NotariatService.AddPersonRelationInfoReq request) {
            return base.Channel.AddPersonRelationInfoAsync(request);
        }
    }
}
